* improve top-level t2 to check if checked out and guide new user after 1st fresh install
git-svn-id: https://svn.exactcode.de/t2/trunk@82420 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/t2 b/t2
--- a/t2
+++ b/t2
@@ -9,7 +9,6 @@ top=$(readlink -f $0)
 [ ! -e t2 -a "$top" ] && cd ${top%/*}
 
 declare -A commands
-
 commands["bootstrap"]="bootstrap vital deps on homebrew systems"
 commands["config"]="creates a target configuration profile"
 commands["install"]="installs a package and its dependencies"
@@ -59,21 +58,28 @@ for a; do
     args+=($a)
 done
 
+# cmd wrapper w/ check if t2 and the matching script was checked out
+exec_checked_w_args() {
+	[ -e $1 ] && exec $* "${args[@]}"
+	echo 'Error: t2 not fully checked out: run "t2 up" to initialize or update.'
+	exit 1
+}
+
 case "$cmd" in
-    conf|config) exec scripts/Config "${args[@]}" ;;
-    bootstrap) exec scripts/Bootstrap "${args[@]}" ;;
-    build) exec scripts/Build-Pkg "${args[@]}" ;;
-    build-target) exec scripts/Build-Target "${args[@]}" ;;
-    clean) exec scripts/Cleanup "${args[@]}" ;;
-    create) exec scripts/Create-Pkg "${args[@]}" ;;
-    create-iso) exec scripts/Create-ISO "${args[@]}" ;;
-    list-errors) exec scripts/Create-ErrList "${args[@]}" ;;
-    commit|ci) exec scripts/Commit "${args[@]}" ;;
-    download|dl) exec scripts/Download "${args[@]}" ;;
-    find) exec scripts/Find-Pkg "${args[@]}" ;;
-    install|inst) exec scripts/Emerge-Pkg "${args[@]}" ;;
-    update) exec scripts/Update-Pkg "${args[@]}" ;;
-    update-system|upgrade) exec scripts/Emerge-Pkg -system "${args[@]}" ;;
+    conf|config) exec_checked_w_args scripts/Config ;;
+    bootstrap) exec_checked_w_args scripts/Bootstrap ;;
+    build) exec_checked_w_args scripts/Build-Pkg ;;
+    build-target) exec_checked_w_args scripts/Build-Target ;;
+    clean) exec_checked_w_args scripts/Cleanup ;;
+    create) exec_checked_w_args scripts/Create-Pkg ;;
+    create-iso) exec_checked_w_args scripts/Create-ISO ;;
+    list-errors) exec_checked_w_args scripts/Create-ErrList ;;
+    commit|ci) exec_checked_w_args scripts/Commit ;;
+    download|dl) exec_checked_w_args scripts/Download ;;
+    find) exec_checked_w_args scripts/Find-Pkg ;;
+    install|inst) exec_checked_w_args scripts/Emerge-Pkg ;;
+    update) exec_checked_w_args scripts/Update-Pkg ;;
+    update-system|upgrade) exec_checked_w_args scripts/Emerge-Pkg -system ;;
     uninstall) exec mine -r "${args[@]}" ;;
     up|pull) if [ -e .git ]; then exec git pull; else exec svn up "${args[@]}"; fi ;;
     *) usage ;;
