* fixed e17-conf.in to not use sed for manipulating configure but setting the proper environment variable to not run configure automatically by autogen.sh and if autogen fails we're going to use our own by setting autogen=1
git-svn-id: https://svn.exactcode.de/t2/trunk@17052 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/package/e17/imlib2/e17-conf.in b/package/e17/imlib2/e17-conf.in
--- a/package/e17/imlib2/e17-conf.in
+++ b/package/e17/imlib2/e17-conf.in
@@ -29,15 +29,18 @@ if [ "$prefix_auto" = 1 ] ; then
 fi
 
 if [ -z "$e17_from_release" ]; then
-# needed since e17 is currently CVS checkout only ...
-# and fixup the damn autogen.sh ...
 
-e17_hacked_autogen() {
-	sed -i -e 's,$USER,stupid,' \
-	       -e 's,\./configure,#./configure,' autogen.sh
-	touch ChangeLog # required automake file sometimes missing ...
-	sh autogen.sh
-	true
+# e17 is CVS only so we have to run the included autogen.sh
+e17_autogen() {
+	# required automake file sometimes missing
+	[ ! -e Changelog ] || touch ChangeLog 
+
+	# exporting NOCONFIGURE=yes to not run ./configure automatically
+	# if the included autogen fails set autogen=1 to use our own ones
+	if ! env NOCONFIGURE=yes sh autogen.sh; then
+		autogen=1
+	fi
 }
-hook_add preconf 5 "[ -e autogen.sh ] && e17_hacked_autogen || true"
+
+hook_add preconf 5 "[ ! -e autogen.sh ] || e17_autogen"
 fi
