* improve scripts/Apply w/ multi arg and local file support
git-svn-id: https://svn.exactcode.de/t2/trunk@93621 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Apply b/scripts/Apply
--- a/scripts/Apply
+++ b/scripts/Apply
@@ -7,17 +7,28 @@
 
 [ "$1" = -help ] && echo "Usage: <url-or-file>" && exit 0
 
-tmp=$(mktemp)
+for f; do
+    tmp=
 
-curl -L "$1" > $tmp
+    case "$f" in
+    http*://*)
+	tmp=$(mktemp)
+    	if ! curl -L "$f" > $tmp; then
+		echo "failed to download $f" >&2
+		rm -f $tmp
+		exit 1
+	fi
+	f=$tmp
+    esac
 
-for p in p0 p1; do
+    for p in p1 p0; do
 	# git apply
-	patch --dry-run -$p < $tmp > /dev/null || continue
-	patch -$p < $tmp && break
-done
+	patch --dry-run -$p < $f > /dev/null || continue
+	patch -$p < $f && break
+    done
 
-toadd=$(sed -n '/.* \(.*\)[[:space:]](nonexistent)/s//\1/p' < $tmp)
+    toadd=$(sed -n '/.* \(.*\)[[:space:]](nonexistent)/s//\1/p' < $tmp)
 [ "$toadd" ] && svn add --parents $toadd
 
-rm -f $tmp
+    [ "$tmp" ] && rm -f $tmp
+done
