* removed superflous whitespace before ; in scripts/ 	  sed -i 's/\([^ ]\) \(;[^;)]\)/\1\2/g' scripts/*
git-svn-id: https://svn.exactcode.de/t2/trunk@50972 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Build-Pkg b/scripts/Build-Pkg
--- a/scripts/Build-Pkg
+++ b/scripts/Build-Pkg
@@ -63,13 +63,13 @@ help_msg() {
 # ---- Parse options + config and make Build-Pkg sub-calls
 #
 
-while [ "$1" ] ; do
+while [ "$1" ]; do
 	case "$1" in
 		-this_is_the_2nd_run) this_is_the_2nd_run=1 ;;
 		-[0-9])   options="$options $1"    ; stagelevel=${1#-} ;;
 		-v)       options="$options $1"    ; verbose=1     ;;
 		-xtrace)  options="$options $1"    ; xtrace=1      ;;
-		-debug)   options="$options $1"    ; debug=1 ; clear_src=0 ;;
+		-debug)   options="$options $1"    ; debug=1; clear_src=0 ;;
 		-update)  options="$options $1"    ; update=1      ;;
 		-chroot)  options="$options $1"    ; chroot=1      ;;
 		-chr-sub) options="$options $1"    ; chroot=0      ;;
@@ -80,15 +80,15 @@ while [ "$1" ] ; do
 		-id)      options="$options $1 $2" ; id="$2"       ; shift ;;
 		-noclearsrc) options="$options $1" ; clear_src=0   ;;
 		-norebuild)  options="$options $1" ; norebuild=1   ;;
-		-*) help_msg ; exit 1 ;;
+		-*) help_msg; exit 1 ;;
 		*)  break ;;
 	esac
 	shift
 done
 
 # check if arguments are left as package names
-if [ $# = 0 ] ; then
-	help_msg ; exit 1
+if [ $# = 0 ]; then
+	help_msg; exit 1
 fi
 
 . scripts/functions.in
@@ -106,7 +106,7 @@ fi
 [ "$root" -a "${root#/}" = "$root" ] && root="$base/$root"
 
 # remove leading and trailing / on prefix and root
-prefix=${prefix%/} ; prefix=${prefix#/} ; root=${root%/}
+prefix=${prefix%/}; prefix=${prefix#/}; root=${root%/}
 
 # xroot is for internal use and always points to the new system
 xroot="$root"
@@ -118,14 +118,14 @@ else
 fi
 
 
-if [ -z "$id" ] ; then
+if [ -z "$id" ]; then
 	id=`get_unique`
 	options="$options -id $id"
 fi
 
 # more than one package is passed
-if [ $# -gt 1 ] ; then
-    for x ; do
+if [ $# -gt 1 ]; then
+    for x; do
 	if ! scripts/Build-Pkg $options $x &&
 	   [ $stagelevel -le $SDECFG_CONTINUE_ON_ERROR_AFTER ]; then
 		exit 1
@@ -133,10 +133,10 @@ if [ $# -gt 1 ] ; then
     done
     exit 0
 fi
-pkg="${1%=*}" ; xpkg="${1#*=}"
+pkg="${1%=*}"; xpkg="${1#*=}"
 builddir="$base/src.$pkg.$config.$id"
 
-if [ "$chroot" = 1 ] ; then
+if [ "$chroot" = 1 ]; then
 
 	cd "$xroot" || exit 1
 
@@ -207,7 +207,7 @@ if [ "$chroot" = 1 ] ; then
 		export SDE_THIS_IS_CHROOT=1
 		chroot "$xroot" /bin/bash TOOLCHAIN/src.$pkg.$config.$id/debug_x.sh
 
-		if ! fuser -s "$xroot/TOOLCHAIN/" ; then
+		if ! fuser -s "$xroot/TOOLCHAIN/"; then
 			echo "Loop mounts appear unused - un-mounting ..."
 			umount "$xroot/TOOLCHAIN/"{loop,config,download}
 			umount "$xroot/proc"
@@ -215,14 +215,14 @@ if [ "$chroot" = 1 ] ; then
 	EOT
 	chmod +x $builddir/debug.sh
 
-	if [ "$TZ" ] ; then
-		if [ "${TZ#/}" != "$TZ" ] ; then
+	if [ "$TZ" ]; then
+		if [ "${TZ#/}" != "$TZ" ]; then
 			cp $TZ TOOLCHAIN/localtime
 		else
 			cp /usr/share/zoneinfo/$TZ TOOLCHAIN/localtime
 		fi
 	else
-		if [ -f /etc/localtime ] ; then
+		if [ -f /etc/localtime ]; then
 			cp /etc/localtime TOOLCHAIN/localtime
 		else
 			ln -sf /usr/share/zoneinfo/Factory TOOLCHAIN/localtime
@@ -245,7 +245,7 @@ fi
 
 scripts/Build-Tools -$stagelevel -cfg $config || exit 1
 
-if [ "$SDECFG_FLIST" = "flwrapper" -a -z "$FLWRAPPER" ] ; then
+if [ "$SDECFG_FLIST" = "flwrapper" -a -z "$FLWRAPPER" ]; then
 	export FLWRAPPER_WLOG="$builddir/fl_wrapper.wlog"
 	export FLWRAPPER_RLOG="$builddir/fl_wrapper.rlog"
 	export FLWRAPPER_BASEPID=$$
@@ -257,14 +257,14 @@ fi
 export INSTALL_WRAPPER_LOGFILE="$builddir/install_wrapper.log"
 export CMD_WRAPPER_LOGFILE="$builddir/cmd_wrapper.log"
 
-if [ $norebuild = 1 -a -f $root/var/adm/logs/$stagelevel-$xpkg.log ] ; then
+if [ $norebuild = 1 -a -f $root/var/adm/logs/$stagelevel-$xpkg.log ]; then
 	echo_pkg_deny $stagelevel $pkg "already built"
 	exit 0
 fi
 
 # TODO: should i be pedantic and force rebuild of low stages even if $norebuild? /mnemoc
 if [ "$SDECFG_RETRY_BROKEN" = 0 -a $norebuild = 1 -a \
-     -f $root/var/adm/logs/$stagelevel-$xpkg.err ] ; then
+     -f $root/var/adm/logs/$stagelevel-$xpkg.err ]; then
 	echo_pkg_deny $stagelevel $pkg "already failed"
 	exit 1
 fi
@@ -273,18 +273,18 @@ archdir="$builddir/archdir"
 
 detect_confdir
 
-if [ -z "$confdir" ] ; then
-	echo_pkg_deny $stagelevel $pkg "does not exist" ; exit 1
+if [ -z "$confdir" ]; then
+	echo_pkg_deny $stagelevel $pkg "does not exist"; exit 1
 fi
 
 mkdir -p $root/var/adm/{logs,flists,olists,md5sums,packages,dependencies,\
 dep-debug,parse-config,cache,descs}
 rm -f $root/var/adm/logs/$stagelevel-$xpkg.{out,log,err}
 
-if [ $this_is_the_2nd_run = 0 ] ; then
+if [ $this_is_the_2nd_run = 0 ]; then
 	[ $stagelevel -gt 1 ] && . /etc/profile
 	options="-this_is_the_2nd_run $options $pkg=$xpkg"
-	if [ "$SDECFG_CREATE_CACHE" = 1 -a $stagelevel -gt 1 ] ; then
+	if [ "$SDECFG_CREATE_CACHE" = 1 -a $stagelevel -gt 1 ]; then
 
 		mkdir -p $root/var/adm/cache
 		rm -f $root/var/adm/cache/$xpkg
@@ -363,7 +363,7 @@ parse_desc $pkg
 
 echo_pkg_start $stagelevel $repository $xpkg $ver $extraver
 
-if [ "$SDECFG_PARANOIA_CHECK" = 1 ] ; then
+if [ "$SDECFG_PARANOIA_CHECK" = 1 ]; then
         x="`scripts/Check-PkgFormat $pkg`"
 	[ "$x" ] && abort "$x\nDisable the 'Paranoia Check' config `
 	                  `option to ignore such errors."
@@ -374,9 +374,9 @@ targetdir="$base/target/$target"
 detect_patchfiles
 
 if [ $stagelevel -gt 1 ]; then
-	for pc_file in $xroot/var/adm/parse-config/* ; do
+	for pc_file in $xroot/var/adm/parse-config/*; do
 		if [ -s "$pc_file" -a "${pc_file##*/}" != "$xpkg" ]
-		then . "$pc_file" ; fi
+		then . "$pc_file"; fi
 	done
 	unset pc_file
 fi
@@ -391,7 +391,7 @@ set --
 eval "$desc_O"
 
 # include package pre config - if any
-if [ -f $base/build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_${pkg}_pre.conf ] ; then
+if [ -f $base/build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_${pkg}_pre.conf ]; then
 	echo_status "Reading build/.../$toolsdir/lib/pkg_${pkg}_pre.conf"
 	. $base/build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_${pkg}_pre.conf
 fi
@@ -410,18 +410,18 @@ for x in $( get_expanded $base/target/%/pkg_$pkg.conf $targetchain ) \
 done
 
 # include package post config - if any
-if [ -f $base/build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_${pkg}_post.conf ] ; then
+if [ -f $base/build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_${pkg}_post.conf ]; then
 	echo_status "Reading build/.../$toolsdir/lib/pkg_${pkg}_post.conf"
 	. $base/build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_${pkg}_post.conf
 fi
 
-if [ -f $base/architecture/$arch/pkg-header ] ; then
+if [ -f $base/architecture/$arch/pkg-header ]; then
 	echo_status "Reading overwrites from architecture/$arch/pkg-header."
 	. $base/architecture/$arch/pkg-header
 fi
 
 for x in $( get_expanded $base/target/%/pkg-header `get_reverted $targetchain` ); do
-	if [ -f $x ] ; then
+	if [ -f $x ]; then
 		echo_status "Reading overwrites from ${x#$base/}."
 		. $x
 	fi
@@ -431,15 +431,15 @@ done
 # ---- Variable updates based on the configuration files read
 #
 
-if [ -z "$prefix" -o "${prefix#usr}" != "$prefix" ] ; then
+if [ -z "$prefix" -o "${prefix#usr}" != "$prefix" ]; then
 	flistdel="$flistdel|usr/share/info/(dir|standards.info)"
-	if [ "$SDECFG_DISABLE_NLS" = 1 ] ; then
+	if [ "$SDECFG_DISABLE_NLS" = 1 ]; then
 		flistdel="$flistdel|usr/share/locale/..[/_].*"
 		flistdel="$flistdel|usr/share/man/..[/_].*"
 	fi
 else
 	flistdel="$flistdel|$prefix/info/(dir|standards.info)"
-	if [ "$SDECFG_DISABLE_NLS" = 1 ] ; then
+	if [ "$SDECFG_DISABLE_NLS" = 1 ]; then
 		flistdel="$flistdel|$prefix/share/locale/..[/_].*"
 		flistdel="$flistdel|$prefix/man/..[/_].*"
 	fi
@@ -451,7 +451,7 @@ fi
 
 echo_status "Preparing build in src.$pkg.$config.$id"
 
-if [ $clear_src = 1 ] ; then
+if [ $clear_src = 1 ]; then
 	mkdir -p $builddir; chmod 700 $builddir
 	if [ "$SDECFG_SRC_TMPFS" = 1 ]; then
 		mount -n -t tmpfs -o $SDECFG_SRC_TMPFS_OPT none $builddir
@@ -460,19 +460,19 @@ else
 	mkdir -p $builddir; chmod 700 $builddir
 fi
 
-if [ $update = 1 -a ! -f $xroot/var/adm/md5sums/$xpkg ] ; then
+if [ $update = 1 -a ! -f $xroot/var/adm/md5sums/$xpkg ]; then
 	echo_status "Ignoring update mode since package isn't installed already."
 	update=0
 fi
 
-if [ $update = 1 ] ; then
+if [ $update = 1 ]; then
 	echo_status "Creating backup of old package data."
 	(
 		cd $xroot/
 		md5sum --check var/adm/md5sums/$xpkg 2>&1 < /dev/null |
 			grep ': FAILED$' | cut -f1 -d:
 	) > $builddir/backup_files.txt
-	if [ -s $builddir/backup_files.txt ] ; then
+	if [ -s $builddir/backup_files.txt ]; then
 		mkdir -p "$xroot/var/adm/backup"
 		chmod 700 "$xroot/var/adm/backup"
 		backup_tar="$xroot/var/adm/backup/$(
@@ -484,10 +484,10 @@ if [ $update = 1 ] ; then
 	fi
 fi
 
-if [ "$SDECFG_FLIST" = "flwrapper" ] ; then
+if [ "$SDECFG_FLIST" = "flwrapper" ]; then
 	rm -f $builddir/fl_wrapper.wlog $builddir/fl_wrapper.rlog
 	touch $builddir/fl_wrapper.wlog $builddir/fl_wrapper.rlog
-elif [ "$SDECFG_FLIST" = "find" ] ; then
+elif [ "$SDECFG_FLIST" = "find" ]; then
 	touch $builddir/temp.time_stamp
 	sleep 2
 fi
@@ -503,7 +503,7 @@ abort() {
 }
 
 {
-	trap 'echo "Got SIGINT (Ctrl-C). Aborting build." ; exit 1' INT
+	trap 'echo "Got SIGINT (Ctrl-C). Aborting build."; exit 1' INT
 	exec < /dev/null
 
 	# Makes debugging build problems easier
@@ -515,9 +515,9 @@ abort() {
 	  cat <<- EOT
 		PS1='\\[\\e[00m\\e[01;31m\\]debug-`
 					`$xpkg\\[\\e[00m\\]:[\\W]\\\$ '
-		alias cp="cp -i" ; alias mv="mv -i"
-		alias rm="rm -i" ; alias ls="ls --color=auto -a"
-		alias ..="cd .." ; alias ...="cd ../.."
+		alias cp="cp -i"; alias mv="mv -i"
+		alias rm="rm -i"; alias ls="ls --color=auto -a"
+		alias ..="cd .."; alias ...="cd ../.."
 		fixfile () {
 		  # we use .vanilla to not rediff backup .orig from patch
 		  for f; do [ -f \$f.vanilla ] || cp \$f{,.vanilla}; done
@@ -561,17 +561,17 @@ abort() {
 	type ${CC}; CMD_WRAPPER_DEBUG=1 ${CC} --version
 	echo "[ writing debug log to $builddir/cmd_wrapper.log ]"
 
-	if [ "$debug" = 1 ] ; then
+	if [ "$debug" = 1 ]; then
 		echo "Everything is set up." \
 		     "We are in debug mode - so exit now."
 		exit
 	fi
 
-	if [ "$SDECFG_FLIST" = "strace" ] ; then
+	if [ "$SDECFG_FLIST" = "strace" ]; then
 		strace -o $builddir/strace.out -F -f -q -e open,creat,mkdir,`
 		       `mknod,link,symlink,rename,utime,chdir,execve,fork,`
                        `vfork,_exit,exit_group -p $(< $builddir/build.pid) &
-                 strace_pid=$! ; sleep 1 ; cd $base
+                 strace_pid=$!; sleep 1; cd $base
 	fi
 
 	(
@@ -581,12 +581,12 @@ abort() {
 		populate_archdir
 
 		echo "Running main build function '$mainfunction' ..."
-		if [ $xtrace -eq 1 -o $SDECFG_XTRACE -eq 1 ] ;	then
-			PS4=$'=[$FUNCNAME:$LINENO (last \\\$?=$?)> ' ; set -o xtrace
-			cd $builddir ; eval "$mainfunction"
+		if [ $xtrace -eq 1 -o $SDECFG_XTRACE -eq 1 ];	then
+			PS4=$'=[$FUNCNAME:$LINENO (last \\\$?=$?)> '; set -o xtrace
+			cd $builddir; eval "$mainfunction"
 			set +o xtrace
 		else
-			cd $builddir ; eval "$mainfunction"
+			cd $builddir; eval "$mainfunction"
 		fi
 		touch $root/var/adm/logs/$stagelevel-$xpkg.log
 	)
@@ -602,26 +602,26 @@ abort() {
 	[ -s "var/adm/parse-config/$xpkg" ] &&
 		echo "var/adm/parse-config/$xpkg" >> $builddir/flist.txt
 	for x in var/adm/{flists,md5sums,packages,descs,dependencies}/$xpkg; do
-		touch $x ; echo "$x" >> $builddir/flist.txt
+		touch $x; echo "$x" >> $builddir/flist.txt
 	done
 	#
-	if [ "$SDECFG_FLIST" = "strace" ] ; then
-		sleep 1 ; kill -INT $strace_pid ; sleep 1
+	if [ "$SDECFG_FLIST" = "strace" ]; then
+		sleep 1; kill -INT $strace_pid; sleep 1
 		fl_stparse -w $builddir/fl_wrapper.wlog \
 			   -r $builddir/fl_wrapper.rlog < $builddir/strace.out
 		
 	fi
 	if [ "$SDECFG_FLIST" = "flwrapper" -o \
-	     "$SDECFG_FLIST" = "strace" ] ; then
+	     "$SDECFG_FLIST" = "strace" ]; then
 		if [ "$stagelevel" -le 1 ]
 		then
-			xbase="$( cd $xroot/ 2> /dev/null ; pwd -P )"
+			xbase="$( cd $xroot/ 2> /dev/null; pwd -P )"
 			flistvalid="$xbase|$flistvalid"
 			
 			if egrep -qv "	($flistvalid)/" $builddir/fl_wrapper.wlog
 			then
-				while read file ; do
-					if [ -e "$file" ] ; then
+				while read file; do
+					if [ -e "$file" ]; then
 						echo "Created file outside basedir: $file"
 						abort_soon=1
 					else # non fatal for now (configure junk)
@@ -658,7 +658,7 @@ abort() {
 		egrep "^(${flistroot// /|})(/|$)" $builddir/flist.txt.tmp >> \
 			 $builddir/flist.txt
 
-	elif [ "$SDECFG_FLIST" = "find" ] ; then
+	elif [ "$SDECFG_FLIST" = "find" ]; then
 		find $flistroot \
 			\( -not -type d -or -type d -empty \) \
 			-and \( -newer $builddir/temp.time_stamp -or \
@@ -703,7 +703,7 @@ abort() {
 	echo -n > var/adm/md5sums/$xpkg
 
 	if [ "$SDECFG_FLIST" = "flwrapper" -o \
-	     "$SDECFG_FLIST" = "strace" ] && [ $stagelevel -gt 1 ] ; then
+	     "$SDECFG_FLIST" = "strace" ] && [ $stagelevel -gt 1 ]; then
 		echo "Calculating package dependencies ..."
 
 		! egrep -v "^($flistrfilter)\$" $builddir/fl_wrapper.[rw]log |
@@ -730,7 +730,7 @@ abort() {
 		sort -u $builddir/dependencies.debug > var/adm/dep-debug/$xpkg
 
 		# merge the dependencies defined by the package
-		for x in `echo "$desc_E" | egrep '^add ' | sed 's/^add //' ` ; do
+		for x in `echo "$desc_E" | egrep '^add ' | sed 's/^add //' `; do
 			echo "Adding dependency: $x ..."
 			echo "$xpkg: $x" >> $builddir/dependencies.txt
 		done
@@ -738,10 +738,10 @@ abort() {
 		# remove dependencies as requested by the package
 		# TODO: goups are not used yet (and it is not easy here)
 		del_pattern=""
-		for x in `echo "$desc_E" | egrep '^del ' | sed 's/^del //' ` ; do
+		for x in `echo "$desc_E" | egrep '^del ' | sed 's/^del //' `; do
 			del_pattern="$del_pattern -e \".*: $x\$\""
 		done
-		if [ -n "$del_pattern" ] ; then
+		if [ -n "$del_pattern" ]; then
 			echo "Deleting dependencies, pattern: $del_pattern ..."
 			eval egrep -v $del_pattern \
 			  $builddir/dependencies.txt > \
@@ -754,7 +754,7 @@ abort() {
 
 	echo -n "Creating md5sum files ..."
 	getfiles < var/adm/flists/$xpkg > $builddir/files.lst
-	if [ -s $builddir/files.lst ] ; then
+	if [ -s $builddir/files.lst ]; then
 		grep -v '^var/adm/' $builddir/files.lst | sed -e 's,^.*,"\0",' |
 			xargs -r md5sum > var/adm/md5sums/$xpkg
 	fi
@@ -806,8 +806,8 @@ EOT
 	(
 	    echo "[CONFIG] ${SDECFG_ID#*-}"
 	    descfile=$base/package/*/$pkg/$pkg.desc
-	    while read x ; do
-		if [ "${x#\[}" != "$x" ] ; then
+	    while read x; do
+		if [ "${x#\[}" != "$x" ]; then
 		    x="`echo ${x// */} | tr -d '[]'`"
 		    y="${x/-/_}"
 		    IFS='
@@ -822,14 +822,14 @@ EOT
 
 	echo "Making post-install adaptions."
 
-	if [ "$SDECFG_PARANOIA_CHECK" = 1 ] ; then
+	if [ "$SDECFG_PARANOIA_CHECK" = 1 ]; then
 		found_errors=0
 		found_dups=0
 
 		# check for files which are 'shared' with other packages
 		if [ "$check_shared" != "0" ]; then
 			while read dummy file; do
-				if [ $found_dups = 0 ] ; then
+				if [ $found_dups = 0 ]; then
 					echo "Found shared files with other packages:"
 					found_errors=1; found_dups=1
 				fi
@@ -843,8 +843,8 @@ EOT
 
 		# check for files in /usr/local
 		if [ "$check_usrlocal" != "0" ]; then
-			while read file ; do
-				if [ $found_local = 0 ] ; then
+			while read file; do
+				if [ $found_local = 0 ]; then
 					echo "Found files in /usr/local:"
 					found_errors=1; found_local=1
 				fi
@@ -882,7 +882,7 @@ EOT
 	echo_status "Building. Writing output to" \
 	            "\$root/var/adm/logs/$stagelevel-$xpkg.out"
 
-	if [ "$SDECFG_VERBOSE" = 1 -o "$verbose" = 1 ] ; then
+	if [ "$SDECFG_VERBOSE" = 1 -o "$verbose" = 1 ]; then
 		tee $root/var/adm/logs/$stagelevel-$xpkg.out |
 		gawk "/$/ {print; printf \"^$stagelevel-$xpkg\r\"; fflush();}"
 	else
@@ -892,16 +892,16 @@ EOT
 
 hook_eval finish
 
-if [ $update = 1 ] ; then
+if [ $update = 1 ]; then
 	echo_status "Restoring backup of old package data."
 
-	while read fn ; do
+	while read fn; do
 		[ -f $xroot/$fn ] && mv $xroot/$fn $xroot/$fn.new
 	done < $builddir/backup_files.txt
 
 	tar --use-compress-program=bzip2 -C $xroot/ -xpf $backup_tar
 
-	while read fn ; do
+	while read fn; do
 		cmp -s $fn $fn.new && rm -f $fn.new
 	done < $builddir/backup_files.txt
 fi
@@ -913,7 +913,7 @@ umount -r -d -f -l $builddir/* 2> /dev/null
 
 if [ "$SDECFG_SRC_TMPFS_LOG" = 1 -a -n "$( type -p df )" ]; then
 	mkdir -p $root/var/adm/t2-debug
-	if [ ! -f $root/var/adm/t2-debug/tmpfslog.txt ] ; then
+	if [ ! -f $root/var/adm/t2-debug/tmpfslog.txt ]; then
 		echo -e "# Config\tPackage\tInodes\tKB" | \
 			expand -t20 > $root/var/adm/t2-debug/tmpfslog.txt
 	fi
@@ -954,7 +954,7 @@ cleanup_src () {
 	rm -rf $builddir/* $builddir
 }
 
-if [ -f $root/var/adm/logs/$stagelevel-$xpkg.log ] ; then
+if [ -f $root/var/adm/logs/$stagelevel-$xpkg.log ]; then
 	cp $root/var/adm/logs/$stagelevel-$xpkg.out $builddir/BUILD-LOG
 	cleanup_src 0
 	mv $root/var/adm/logs/$stagelevel-$xpkg.out \
@@ -964,7 +964,7 @@ if [ -f $root/var/adm/logs/$stagelevel-$xpkg.log ] ; then
 else
 	cp $root/var/adm/logs/$stagelevel-$xpkg.out $builddir/ERROR-LOG
 	cleanup_src 1
-	if [ "$SDECFG_VERBOSE" != 1 -a "$verbose" != 1 ] ; then
+	if [ "$SDECFG_VERBOSE" != 1 -a "$verbose" != 1 ]; then
 		echo_errorquote "$( grep -v 'make[^ ]*:' \
 			$root/var/adm/logs/$stagelevel-$xpkg.out |
 			grep -B8 -- '--- BUILD ERROR ---' |
