added more post build file layout checks to Build-Target
git-svn-id: https://svn.exactcode.de/t2/trunk@526 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Build-Target b/scripts/Build-Target
--- a/scripts/Build-Target
+++ b/scripts/Build-Target
@@ -204,7 +204,8 @@ fi
 		   ! [ $ROCKCFG_CREATE_GEM = 0 -o \
 				-e build/$ROCKCFG_ID/pkgs/$x.gem ]
 		then
-			echo_error "$x binary package is missing!"
+			x="build/$ROCKCFG_ID/pkgs/$x"	
+			echo_error "Binary package $x is missing!"
 			errors=1
 		fi
 	done
@@ -213,11 +214,44 @@ fi
 		[ $ROCKCFG_CREATE_GEM = 0 ] || x=${x%.gem}
 		[ $ROCKCFG_CREATE_TARBZ2 = 0 ] || x=${x%.tar.bz2}
 		if ! grep -qx "$x" $pkglst ; then
+			file="build/$ROCKCFG_ID/pkgs/$file"
 			echo_error "$file should not be present (now in src/invalid-files.lst)!"
 			mkdir -p src; echo "$file" >> src/invalid-files.lst
 			errors=1
 		fi
 	done
+	echo_header "Searching for old cache,cksums,dependencies,descs,flists,md5sums,packages files ..."
+	for dir in build/$ROCKCFG_ID/root/var/adm/{cache,cksums,dependencies,descs,flists,md5sums,packages} ; do
+		echo $dir
+		for file in `cd $dir; echo *` ; do
+			if [ $ROCKCFG_PKGFILE_VER ] ; then
+				x=$file-
+			else 
+				x=$file.
+			fi	
+			if ! grep -q "$x" $pkglst ; then
+				echo_error "$dir/$file should not be present (now in src/invalid-files.lst)!"
+				mkdir -p src; echo "$dir/$file" >> src/invalid-files.lst
+				errors=1
+			fi
+		done
+	done
+	for file in `cd build/$ROCKCFG_ID/root/var/adm/logs/; echo *` ; do
+			x="`echo $file | sed -e 's/^.-//' -e 's/\.log//' -e 's/\.err//' -e s'/\.out//'`"
+			if [ $ROCKCFG_PKGFILE_VER ] ; then
+				x=$x-
+			else
+				x=$x.
+			fi
+
+		if ! grep -q "$x" $pkglst ; then
+			file="build/$ROCKCFG_ID/root/var/adm/logs/$file"
+			echo_error "$file should not be present (now in src/invalid-files.lst)!"
+			mkdir -p src; echo "$file" >> src/invalid-files.lst
+			errors=1
+		fi
+	done
+
 	[ $errors = 0 ] && echo_status "No errors found."
 	rm $pkglst
 }
