new unchroot output plugin adaptions and a html output plugin (#21)
git-svn-id: https://svn.exactcode.de/t2/trunk@1142 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Build-Pkg b/scripts/Build-Pkg
--- a/scripts/Build-Pkg
+++ b/scripts/Build-Pkg
@@ -583,7 +583,7 @@ abort() {
 }
 
 {
-	trap 'echo "Got SIGIN (Crtl-C). Aborting build." ; exit 1' INT
+	trap 'echo "Got SIGINT (Crtl-C). Aborting build." ; exit 1' INT
 	exec < /dev/null
 
 	# Makes debugging build problems easier
@@ -602,7 +602,7 @@ abort() {
 	#
 	{	echo "#!/bin/bash"
 		echo "export PROMPT_COMMAND='. debug.buildenv ; cd . ;" \
-		     "unset PROMPT_COMMAND'" ; echo "exec bash 3> build.pid"
+		     "unset PROMPT_COMMAND'" ; echo "exec bash 200>> build.pid"
 	} > $builddir/debug.sh
 	chmod +x $builddir/debug.sh
 
@@ -617,7 +617,7 @@ abort() {
 	# of this build process.
 	#
 	sh -c 'echo $PPID' > $builddir/build.pid
-	exec 3>> $builddir/build.pid
+	exec 200>> $builddir/build.pid
 
 	echo "Command Wrapper Debug: running '${CC} --version' .."
 	type ${CC}; CMD_WRAPPER_DEBUG=1 ${CC} --version
