* added "where" text arguments to two uncommented aborts in Build-Pkg 	  to save hours of tracking what is actually going wrong ;-)
git-svn-id: https://svn.exactcode.de/t2/trunk@4358 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Build-Pkg b/scripts/Build-Pkg
--- a/scripts/Build-Pkg
+++ b/scripts/Build-Pkg
@@ -590,7 +590,8 @@ abort() {
 		fi
 		touch $root/var/adm/logs/$stagelevel-$xpkg.log
 	)
-	[ ! -f $root/var/adm/logs/$stagelevel-$xpkg.log ] && abort
+	[ -f $root/var/adm/logs/$stagelevel-$xpkg.log ] \
+	  || abort "No $stagelevel-$xpkg.log file."
 
 	hook_eval postinstall
 
@@ -833,7 +834,7 @@ EOT
 			done < <( grep -f $builddir/badfiles.txt $root/var/adm/flists/$xpkg )
 		fi
 
-		[ $found_errors != 0 ] && abort
+		[ $found_errors != 0 ] && abort "Due to previous errors."
 	fi
 
 } 2>&1 | {
