* slightly more modern Build-Tools code style: 	* use shell expansion for two more wrapper rename 	* remove superflous empty # comment lines
git-svn-id: http://svn.exactcode.de/t2/trunk@67024 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Build-Tools b/scripts/Build-Tools
--- a/scripts/Build-Tools
+++ b/scripts/Build-Tools
@@ -98,15 +98,13 @@ if [ ! -f build/$SDECFG_ID/TOOLCHAIN/$toolsdir/.lastupdate ]; then
 	echo_header "Building tools in build/.../TOOLCHAIN/$toolsdir:"
 
 	# CC, CXX, F77 and KCC Wrapper
-	#
-	wrappers="cmd_wrapper" wrappervars=""
+	wrappers="cmd_wrapper" wrappervars=
 	echo_status "Building $toolsdir/wrapper/cmd_wrapper"
 	$BUILDCC -Wall -O2 misc/tools-source/cmd_wrapper.c \
 		  -DENVPREFIX='"CMD"' -DMYNAME='"cmd_wrapper"' \
 	          -o build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/tmp.$$ || exit 1
-	mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/tmp.$$ \
-	   build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/cmd_wrapper
-	#
+	mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/{tmp.$$,cmd_wrapper}
+
 	build_wrapper() {
 	    local x="$(echo ${1//,/ })" y z
 	    wrappervars="$wrappervars $x"
@@ -163,16 +161,16 @@ if [ ! -f build/$SDECFG_ID/TOOLCHAIN/$toolsdir/.lastupdate ]; then
 		mv $tmp "build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/$1"
 	    done
 	}
-	#
+
 	while read script; do . $script
 	done < <(bash scripts/xfind.sh package/. \
 		$(get_reverted `get_expanded target/%/. $targetchain`) misc/. -name 'wrappers.in')
-	#
+
 	echo_status "Building $toolsdir/wrapper/strip_wrapper"
 	cat << EOT > build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/strip_wrapper.$$
 #!/usr/bin/env bash
 if [ "\$STRIP_WRAPPER_NOLOOP" = 1 ]; then
-	echo "Aaaaaeik! Strip wrapper is looping!" >&2
+	echo "Error: Strip wrapper is looping!" >&2
 	exit 1
 fi
 if [ "\$SDECFG_DEBUG" = 0 -o "\$STRIP_WRAPPER_BYPASS" = 1 ]; then
@@ -183,16 +181,15 @@ fi
 exit 0
 EOT
 	chmod +x build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/strip_wrapper.$$
-	mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/strip_wrapper.$$ \
-	   build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/strip_wrapper
+	mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/strip_wrapper{.$$,}
 	wrappers="$wrappers strip_wrapper"
-	#
+
 	for x in strip $arch_target-strip; do
 		[ $crossnative = cross -a $x = strip ] && continue
 		ln -sf strip_wrapper build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/$x
 		wrappers="$wrappers $x"
 	done
-	#
+
 	case $arch_target in
 		*mingw32*)	uname_machine=MINGW32 ;;
 		*darwin*)	uname_machine=Darwin ;;
@@ -252,7 +249,7 @@ EOT
 	mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/arch{.$$,}
 	mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/uname{.$$,}
 	wrappers="$wrappers arch uname"
-	#
+
 	if [ $crossnative = cross ]; then
 		echo_status "Building $toolsdir/wrapper/ldconfig"
 		cat << EOT > build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/ldconfig.$$
@@ -263,7 +260,7 @@ EOT
 		mv build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/ldconfig{.$$,}
 		wrappers="$wrappers ldconfig"
 	fi
-	#
+
 	echo_status "Building $toolsdir/wrapper/install_wrapper"
 	cp misc/tools-source/install_wrapper.sh build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/install_wrapper
 	chmod +x build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/install_wrapper
@@ -272,7 +269,7 @@ EOT
 	ln -sf install_wrapper build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/ln
 	ln -sf install_wrapper build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/mv
 	wrappers="$wrappers install_wrapper install cp ln mv"
-	#
+
 	# Remove unknown, spurious wrappers from potential prev. run
 	wrappers=" $wrappers " # add whitespace for quick match below
 	for w in $(ls build/$SDECFG_ID/TOOLCHAIN/$toolsdir/wrapper/); do
@@ -281,7 +278,6 @@ EOT
 	done
 
 	# Various small tools
-	#
 	for x in getdu getfiles fl_wrparse fl_stparse; do
 		echo_status "Building $toolsdir/bin/$x"
 		$BUILDCC -Wall -O2 misc/tools-source/$x.c \
@@ -291,7 +287,6 @@ EOT
 	done
 
 	# Flist Wrapper Library
-	#
 	if [ "$SDECFG_FLIST" = "flwrapper" ]; then
 		echo_status "Building $toolsdir/lib/fl_wrapper.so"
 
@@ -339,7 +334,6 @@ EOT
 	fi
 
 	# Create Parse-Config Collection
-	#
 	echo_status "Creating $toolsdir/lib/parse-config"
 	bash scripts/xfind.sh \
 	     architecture/$arch/. kernel/$kernel/. package/. $(get_reverted `get_expanded target/%/. $targetchain`) misc/ -type f \
@@ -360,7 +354,6 @@ EOT
 	   build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/parse-config-fixarch
 
 	# Create pkg_*_{pre,post}.conf files
-	#
 
 	echo_status "Creating $toolsdir/lib/pkg_*_{pre,post}.conf"
 	rm -f build/$SDECFG_ID/TOOLCHAIN/$toolsdir/lib/pkg_*_{pre,post}.conf
