Clifford Wolf <clifford@clifford.at> - [Patch] 200305261154
git-svn-id: https://svn.exactcode.de/t2/rock-trunk@396 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Build-Target b/scripts/Build-Target
--- a/scripts/Build-Target
+++ b/scripts/Build-Target
@@ -189,6 +189,37 @@ fi
 		done
 	    fi
 	fi
+
+	local pkglst=`mktemp` errors=0; rm -f src/invalid-files.lst
+	echo_header "Searching for missing or old versioned binary packages ..."
+	grep "^X" config/$config/packages |
+	if [ $ROCKCFG_PKGFILE_VER = 1 ] ; then
+		cut -d' ' -f5-6 | sed "s/ /-/"
+	else
+		cut -d' ' -f5
+	fi > $pkglst
+	for x in `cat $pkglst` ; do
+		if ! [ $ROCKCFG_CREATE_TARBZ2 = 0 -o \
+				-e build/$ROCKCFG_ID/pkgs/$x.tar.bz2 ] ||
+		   ! [ $ROCKCFG_CREATE_GEM = 0 -o \
+				-e build/$ROCKCFG_ID/pkgs/$x.gem ]
+		then
+			echo_error "$x binary package is missing!"
+			errors=1
+		fi
+	done
+	for file in `cd build/$ROCKCFG_ID/pkgs/; echo *` ; do
+		x="$file"
+		[ $ROCKCFG_CREATE_GEM = 0 ] || x=${x%.gem}
+		[ $ROCKCFG_CREATE_TARBZ2 = 0 ] || x=${x%.tar.bz2}
+		if ! grep -qx "$x" $pkglst ; then
+			echo_error "$file should not be present (now in src/invalid-files.lst)!"
+			mkdir -p src; echo "$file" >> src/invalid-files.lst
+			errors=1
+		fi
+	done
+	[ $errors = 0 ] && echo_status "No errors found."
+	rm $pkglst
 }
 
 # Process one line of output generated by Create-PkgQueue
