* partially revert r58264, bail w/o config if people try to emerge 	  t2 sources on foreign distributions, ...
git-svn-id: https://svn.exactcode.de/t2/trunk@58278 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Config b/scripts/Config
--- a/scripts/Config
+++ b/scripts/Config
@@ -65,6 +65,12 @@ if [ ! -d config/$config -a -e /etc/SDE-CONFIG/config -a $config = default ]; th
 		config/$config/config
 fi
 
+if [ ! -d config/$config -a -n "$oldconfig" ]; then
+	echo "Error: -oldconfig is not supported for a new config"
+	echo
+	exit 1
+fi
+
 if [ $delete_mode = 1 ]; then
 	rm -rv config/$config
 	exit $?
