* improved Config to accept -oldconfig only for old configs, stoping typos.
git-svn-id: http://svn.exactcode.de/t2/trunk@14279 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Config b/scripts/Config
--- a/scripts/Config
+++ b/scripts/Config
@@ -43,6 +43,7 @@ show_usage() {
 	echo "	-nobashmod	don't use the bash config helper plugin"
 	echo
 }
+
 while [ "$1" ] ; do
         case "$1" in
 	    -cycle)	do_config_cycle=1 ; shift ;;
@@ -59,6 +60,12 @@ done
 
 if [ -z "$config" ]; then
 	show_usage
+	exit 1
+fi
+
+if [ ! -d config/$config -a -n "$oldconfig" ]; then
+	echo "Abort: -oldconfig is not supported for new configs"
+	echo
 	exit 1
 fi
 
