* reimplemented the former C Config accelerator in LUA and integrated it 	  instead into the Config using Valentin's luabash bridge, can be used for 	  further Config rewrite and speedup
git-svn-id: https://svn.exactcode.de/t2/trunk@20094 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Config b/scripts/Config
--- a/scripts/Config
+++ b/scripts/Config
@@ -30,7 +30,6 @@ config=default
 do_config_cycle=0
 delete_mode=0
 oldconfig=''
-nobashmod=''
 cfgtmpdir=''
 profile=""
 
@@ -40,7 +39,6 @@ show_usage() {
 	echo
 	echo "Other options:"
 	echo "	-profile	create a config.profile with profiling data"
-	echo "	-nobashmod	don't use the bash config helper plugin"
 	echo
 }
 
@@ -50,7 +48,6 @@ while [ "$1" ] ; do
 	    -delete)	delete_mode=1     ; shift ;;
 	    -profile)	profile='-profile'        ; shift ;;
 	    -oldconfig)	oldconfig='-oldconfig'    ; shift ;;
-	    -nobashmod)	nobashmod='-nobashmod'    ; shift ;;
 	    -cfg)	config="$2"       ; shift ; shift ;;
 
 	    *)  show_usage
@@ -104,20 +101,28 @@ if [ $do_config_cycle = 0 ] ; then
 	fi
 
 	echo "T2 $sdever configuration ..."
-	while "$0" -cfg $config $oldconfig $profile $nobashmod -cycle ; do : ; done
+	while "$0" -cfg $config $oldconfig $profile -cycle ; do : ; done
 
 	trap INT
 
 	exit 0
 fi
 
-if [ -z "$nobashmod" ]; then
-	if [ ! -f src/config_helper.so -o misc/tools-source/config_helper.c -nt src/config_helper.so ]; then
-		echo "Building src/config_helper.so."
-		gcc -shared -fPIC -Wall -o src/config_helper.so misc/tools-source/config_helper.c || exit 1
-	fi
-	enable -f src/config_helper.so cfghlp || exit 1
+echo "Building src/luabash.so."
+rm -rf src/luabash.so
+make -C misc/luabash/ && install misc/luabash/luabash.so src/
+
+if [ ! -f src/luabash.so ]; then
+	echo "Error building the LUA bash accelerator."
+	exit 1
 fi
+
+if ! enable -f src/luabash.so luabash; then
+	echo "Failed to enable the LUA bash accelerator"
+	exit 1
+fi
+
+luabash load scripts/config-functions.lua || exit 1
 
 if [ -z "$profile" ]; then
 	bprof() { :; }
