* improved Config to abort if the backup fails
git-svn-id: https://svn.exactcode.de/t2/trunk@16322 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Config b/scripts/Config
--- a/scripts/Config
+++ b/scripts/Config
@@ -92,6 +92,10 @@ if [ $do_config_cycle = 0 ] ; then
 		echo "Backing up existing config/$config/* ..."
 		mkdir -p $cfgtmpdir/backup
 		cp -a config/$config/* $cfgtmpdir/backup
+		if [ $? -ne 0 ]; then
+			echo "Backup failed, aborting."
+			exit 1
+		fi
 	fi
 
 	echo "T2 $sdever configuration ..."
