* normalize some more leading spaces in scripts/, too
git-svn-id: http://svn.exactcode.de/t2/trunk@59446 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Create-PkgUpdPatch b/scripts/Create-PkgUpdPatch
--- a/scripts/Create-PkgUpdPatch
+++ b/scripts/Create-PkgUpdPatch
@@ -20,9 +20,9 @@ if [ -z "$ver" ]; then
 fi
 
 if [ -z "$pkg" -o -z "$ver" ]; then
-        echo "Usage: $0 pkg ver"
-        echo "   or: $0 pkg-ver"
-        exit
+	echo "Usage: $0 pkg ver"
+	echo "   or: $0 pkg-ver"
+	exit
 fi
 
 pkg=`echo $pkg | tr A-Z a-z`
@@ -31,7 +31,7 @@ echo "[ $pkg ]" >&2
 pkgdir=`echo package/*/$pkg`
 
 if [ ! -d "$pkgdir" ]; then
-        echo "Can't find package for '$x'!" >&2
+	echo "Can't find package for '$x'!" >&2
 else
 	oldver="`egrep "^\[(V|VER|VERSION)\] " $pkgdir/$pkg.desc |
 			sed 's, ,\t,g; s,\t\t*,\t,g' | cut -f2`"
