* improved scripts/Create-ISO mkisofs diagnostics
git-svn-id: https://svn.exactcode.de/t2/trunk@63370 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Create-ISO b/scripts/Create-ISO
--- a/scripts/Create-ISO
+++ b/scripts/Create-ISO
@@ -303,13 +303,13 @@ mkisofs=
 for x in xorrisofs genisoimage mkisofs; do
 	if [ "`type -p $x`" ]; then
 		if [[ $x = "xorrisofs" && "$bootoptions" = *-hfs* ]]; then
-			echo "$x does not yet support -hfs, ... skipped."
+			echo "Warning: $x does not yet support -hfs, skipped!"
 		else
 			mkisofs="$x"; break
 		fi
 	fi
 done
-[ ! "$mkisofs" ] && echo 'No "mkisofs" found in path!' && exit 1
+[ ! "$mkisofs" ] && echo 'Error: No suitable "mkisofs" found!' && exit 1
 
 for x in $disks; do
 	ds=disk_${x}_size
