* reworked scripts/Create-PkgUpdPatch to primarily accept input in the 	  form pkg ver - and only pkg-ver as fallback 	* also removed iterating in shell code over all the packages 	* removed mulitple updates at-a-time support
git-svn-id: http://svn.exactcode.de/t2/trunk@9264 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Create-PkgUpdPatch b/scripts/Create-PkgUpdPatch
--- a/scripts/Create-PkgUpdPatch
+++ b/scripts/Create-PkgUpdPatch
@@ -5,7 +5,6 @@
 # 
 # T2 SDE: scripts/Create-PkgUpdPatch
 # Copyright (C) 2004 - 2005 The T2 SDE Project
-# Copyright (C) 1998 - 2003 ROCK Linux Project
 # 
 # More information can be found in the files COPYING and README.
 # 
@@ -15,52 +14,37 @@
 # GNU General Public License can be found in the file COPYING.
 # --- T2-COPYRIGHT-NOTE-END ---
 
-if [ "$1" != "${1#-}" ] ; then
-	cat << EOT >&2
+pkg="$1" ; shift
+ver="$1" ; shift
 
-$0:
-Script for automatically creating package-update patches
-
-Input format (e.g.): automake-1.5, bind-9.2.0rc3, binutils-2.11.90.0.31,
-                     gettext-0.10.40, gnome-applets-1.4.0.4
-
-Output format: unified diff for the .desc files
-
-EOT
-	exit 1
+if [ -z "$ver" ]; then
+	ver=${pkg/*-/}
+	pkg=${pkg%-$ver}
 fi
 
-if [ "$*" ] ; then
-	echo "$*" | exec $0
-	exit $?
+if [ -z "$pkg" -o -z "$ver" ]; then
+        echo "Usage: $0 pkg ver"
+        echo "   or: $0 pkg-ver"
+        exit
 fi
 
-tr ', \t' '\n\n\n' |
-tr -s '\n' | 
-while read x ; do
-	pkg="" ; pkgdir=""
-	[ -z "$x" ] && continue
+pkg=`echo $pkg | tr [A-Z] [a-z]`
 
-	echo "[ $x ]" >&2
-	for y in package/*/* ; do
-		z=${y##*/}
-		if [[ "$x" == "$z"[-_]* ]] ; then
-			pkg="$z" ; pkgdir="$y"
-		fi
-	done
-	if [ "$pkg" ] ; then
-		oldver="`egrep "^\[(V|VER|VERSION)\] " $pkgdir/$pkg.desc |
-				tr '\t' ' ' | tr -s ' ' | cut -f2 -d' '`"
-		newver=${x/$pkg?/} ; tmpfile=`mktemp` ; tmpfile2=`mktemp`
-		echo "Upgrade Patch for $pkg ($pkgdir): $oldver -> $newver"
-		sed "s/${oldver//./\\.}/$newver/g" < $pkgdir/$pkg.desc | \
-		sed "s/^\[\(D\|DOWN\|DOWNLOAD\)\] [0-9]\+/[\1] 0/" > $tmpfile
-		diff -u ./$pkgdir/$pkg.desc $tmpfile | tee $tmpfile2
-		[ -s $tmpfile2 ] || echo "Patch for '$x' is empty!" >&2
-		rm -f $tmpfile $tmpfile2
-	else
-		echo "Can't find package for '$x'!" >&2
-		echo "Can't find package for '$x'!"
-	fi
-	echo
-done
+echo "[ $pkg ]" >&2
+pkgdir=`echo package/*/$pkg`
+
+if [ ! -d "$pkgdir" ] ; then
+        echo "Can't find package for '$x'!" >&2
+else
+	oldver="`egrep "^\[(V|VER|VERSION)\] " $pkgdir/$pkg.desc |
+			tr '\t' ' ' | tr -s ' ' | cut -f2 -d' '`"
+	tmpfile=`mktemp` ; tmpfile2=`mktemp`
+	echo "Update patch for $pkg ($pkgdir): $oldver -> $ver"
+	sed "s/${oldver//./\\.}/$ver/g" < $pkgdir/$pkg.desc | \
+	sed "s/^\[\(D\|DOWN\|DOWNLOAD\)\] [0-9]\+/[\1] 0/" > $tmpfile
+	diff -u ./$pkgdir/$pkg.desc $tmpfile | tee $tmpfile2
+	[ -s $tmpfile2 ] || echo "Patch for '$x' is empty!" >&2
+	rm -f $tmpfile $tmpfile2
+fi
+echo
+
