Clifford Wolf <clifford@clifford.at>: the attached patch fixes the *.Z to *.bz2 conversion in the Download script. with that patch applied it's possible again to e.g. build xfree86 after a fresh download ...
git-svn-id: https://svn.exactcode.de/t2/trunk@1492 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -504,7 +504,7 @@ download_file() {
 				  typeexpr="gzip compressed data" ;;
 			      *.bz2|*.tbz2)
 				  typeexpr="bzip2 compressed data" ;;
-			      *.Z)
+			      *.Z|*.tZ)
 				  typeexpr="compress'd data" ;;
 			      *.zip|*.jar)
 				  typeexpr="Zip archive data" ;;
@@ -638,7 +638,7 @@ list() {
 
 list_unknown() {
 	trap '' INT
-	mkdir -p src/ ; list | sed 's,\.\(t\?\)gz$,.\1bz2,' > src/down.$$.lst
+	mkdir -p src/ ; list | sed 's,\.\(t\?\)\(gz\|Z\)$,.\1bz2,' > src/down.$$.lst
 	ls download/{INDEX,README,DOWNTEST,LAST-UPDATE} \
 						>> src/down.$$.lst 2> /dev/null
 	find download/* -type f -o -type l | \
@@ -651,7 +651,7 @@ list_unknown() {
 
 list_missing() {
 	trap '' INT
-	list | sed 's,\.\(t\?\)gz$,.\1bz2,' | \
+	list | sed 's,\.\(t\?\)\(gz\|Z\)$,.\1bz2,' | \
 	while read fn ; do
 		[ -f "$fn" ] || echo "$fn"
 	done
@@ -702,11 +702,13 @@ required() {
 
 single_files() {
     for file_name ; do
-	if ! handle_file "$file_name" ; then
-		file_name="`echo "$file_name" | sed 's,\.\(t\?\)bz2$,.\1gz,'`"
-		if ! handle_file "$file_name" ; then
-			echo "ERROR: Unknown file: $file_name."
-		fi
+	file_name_gz="`echo "$file_name" | sed 's,\.\(t\?\)bz2$,.\1gz,'`"
+	file_name_Z="`echo "$file_name" | sed 's,\.\(t\?\)bz2$,.\1Z,'`"
+	if ! handle_file "$file_name"    && \
+	   ! handle_file "$file_name_gz" && \
+	   ! handle_file "$file_name_Z"
+	then
+		echo "ERROR: Unknown file: $file_name."
 	fi
     done
 }
