Clifford Wolf: 	Minor scripts/Download changes for new mirrors
[2004070617191901329] (https://www.rocklinux.net/submaster)



git-svn-id: https://svn.exactcode.de/t2/trunk@3521 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -400,17 +400,12 @@ download_file() {
 		    #
 		    mirror="$( cat download/Mirror )"
 
-		    if [ "$mirror" -a "$mirror" != "none" ] ; then
+		    if [ -n "$mirror" -a "$mirror" != "none" -a -z "${bzfile##download/mirror/*}" ] ; then
 			# try to use mirror
 
-			if ! download_file_now "!$mirror/${bzfile#download/}" $bzfile $bzfile; then
-				#FIXME: compatibility, can be removed sooner or later...
-				# Try old download format for remote file
-				if ! download_file_now "!$mirror/$repo${pkg:+/}$pkg/`basename $bzfile`" $bzfile $bzfile; then
-					# oops... so try direct (original URL)
-					echo "INFO: download from mirror failed, trying original URL."
-					download_file_now $location $gzfile $bzfile
-				fi
+			if ! download_file_now "!$mirror/${bzfile#download/mirror/}" $bzfile $bzfile; then
+				echo "INFO: download from mirror failed, trying original URL."
+				download_file_now $location $gzfile $bzfile
 			else
 				gzfile="$bzfile"
 			fi
