* more consistent help Usage: across all scripts/
git-svn-id: https://svn.exactcode.de/t2/trunk@92585 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -24,29 +24,22 @@ base=$(pwd -P)
 
 usage() {
     if [ "$1" = 1 ]; then
-	{ echo
-	echo "Usage:"
+	echo "Usage: [ options ] [ .desc file ] [ -repository repo ] [ -all | -required ] [ packages ]"
 	echo
-	echo " scripts/Download [options] [ Package(s) ]"
-	echo " scripts/Download [options] [ Desc file(s) ]"
-	echo " scripts/Download [options] -repository Repositories"
-	echo " scripts/Download [options] { -all | -required }"
-	echo
-	echo " Where [options] is an alias for:"
+	echo "Where [options] is an alias for:"
 	echo "    [ -cfg <config> ] [ -nock ]  [ -alt-dir <AlternativeDirectory> ]"
 	echo "    [ -mirror <URL> | -check ]  [ -try-questionable ]  [ -notimeout ]"
 	echo "    [ -longtimeout ]  [ -curl-opt <curl-option>[:<curl-option>[:..]] ]"
 	echo "    [ -proxy <server>[:<port>] ] [ -proxy-auth <username>[:<password>] ]"
 	echo "    [ -copy ] [ -move ]"
 	echo
-	echo " On default, this script auto-detects the best T2 SDE mirror."
+	echo "By default, this script auto-detects the best T2 SDE mirror."
 	echo
-	echo " Mirrors can also be a local directories in the form of: 'file:///<dir>'"
+	echo "Mirrors can also be a local directories in the form of: 'file:///<dir>'"
 	echo
-	echo " scripts/Download -mk-cksum Filename(s)"
-	echo " scripts/Download [ -list | -list-unknown | -list-missing | -list-cksums ]"
-	echo; } >&2
-    fi
+	echo "-mk-cksum Filename(s)"
+	echo "[ -list | -list-unknown | -list-missing | -list-cksums ]"
+    fi >&2
 
     exit $1
 }
