* improved Download to unsign .gpg files
git-svn-id: https://svn.exactcode.de/t2/trunk@8087 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -428,6 +428,19 @@ download_file() {
 		fi
 	fi
 
+	# unsign .gpg file
+	if [[ $gzfile = *.gpg ]]; then
+		gzfile=${gzfile%.gpg}
+		if [ -f $gzfile.gpg ]; then
+			echo "unsigning GnuPG file: $gzfile.gpg"
+			gpg $gzfile.gpg
+		fi
+		if [ ! -f $gzfile ]; then
+			echo "unsigning failed"
+			rm -f "$lkfile" ; trap INT ; return 1
+		fi
+	fi
+
 	case "$gzfile" in
 		# Convert a .gz to .bz2 and test checksum
 		#
