* further clean up scripts/Download removing quotes around one $? and fix gramar
git-svn-id: https://svn.exactcode.de/t2/trunk@61990 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -603,7 +603,7 @@ download_file_now() {
 		# so I use this function again with a modified
 		# download location.
 		download_file_now "$location" $gzfile $bzfile
-		return "$?"
+		return $?
 		;;
 	http://*|https://*|ftp://*|file://*)
 		if [ -s "$gzfile.incomplete" ]; then
@@ -978,7 +978,7 @@ if [ "${1:0:5}" != "-list" -a $checkonly = 0 ]; then
 
 	# We need curl
 	if [ -z "`type -p curl`" ]; then
-		echo "ERROR: we need \`curl\` installed and available on \$PATH to proceed."
+		echo "ERROR: we need \`curl\` installed and available in \$PATH to proceed."
 		exit 2
 	fi
 
