Alejandro Mery <amery@geeks.cl>: detect mirror only when it will be used force config only when downloading requireds
git-svn-id: https://svn.exactcode.de/t2/trunk@2054 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -234,14 +234,6 @@ cksum_chk() {
 	return 0
 }
 
-# Choosen config must exist
-#
-if [ ! -f config/$config/packages ]; then
-	echo "ERROR: Config $config doesn't exist."
-	echo "ERROR: try ./scripts/Config -cfg $config first."
-	exit 1
-fi
-
 # Autodetect best Mirror and safe url in $mirror
 #
 detect_mirror() {
@@ -749,6 +741,14 @@ repository() {
 }
 
 required() {
+    # Choosen config must exist
+    #
+    if [ ! -f config/$config/packages ]; then
+        echo "ERROR: Config $config doesn't exist."
+        echo "ERROR: try ./scripts/Config -cfg $config first."
+        exit 1
+    fi
+
     while read on a b tree pkg c ; do
 	if [ "$on" = "X" ] ; then
 	    grep -H '^\[D\] ' package/$tree/$pkg/$pkg.desc > src/down.$$.lst
@@ -788,7 +788,7 @@ all() {
 
 # Do mirror detection only once
 #
-if [ $this_is_the_2nd_run = 0 ]; then
+if [ $this_is_the_2nd_run = 0 -a "${1:0:5}" != "-list" -a $checkonly = 0 ]; then
 	detect_mirror
 fi
 
