* improved Download to check for 'curl' presence.
git-svn-id: https://svn.exactcode.de/t2/trunk@6722 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -808,6 +808,12 @@ if [ "${1:0:5}" != "-list" -a $checkonly = 0 ]; then
  		fi
  	fi
 
+	# we need curl
+	if [ -z "`type -p curl`" ]; then
+		echo "ERROR: we need \`curl\` installed and available on \$PATH to proceed."
+		exit 2
+	fi
+
 	# Thing to do only once 
 	#
 	if [ $this_is_the_2nd_run = 0 ]; then
