* normalize some more leading spaces in scripts/, too
git-svn-id: https://svn.exactcode.de/t2/trunk@59446 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Download b/scripts/Download
--- a/scripts/Download
+++ b/scripts/Download
@@ -198,9 +198,9 @@ done
 # Read some config values
 
 target=`grep '^export SDECFG_TARGET=' config/$config/config 2>/dev/null |
-        cut -f2 -d= | tr -d "'"`
+	cut -f2 -d= | tr -d "'"`
 arch=`grep '^export SDECFG_ARCH=' config/$config/config 2>/dev/null |
-        cut -f2 -d= | tr -d "'"`
+	cut -f2 -d= | tr -d "'"`
 arch="${arch:-none}" target="${target:-none}"
 
 
@@ -239,10 +239,10 @@ cksum_chk() {
 	y="${y#\{$ck\}}"
 
 	local cksum=${ck}sum
-        if ! type -p $cksum > /dev/null; then
-            cksum=${cksum#sha} cksum=${cksum%sum}
-            cksum="shasum -a $cksum"
-        fi
+	if ! type -p $cksum > /dev/null; then
+	    cksum=${cksum#sha} cksum=${cksum%sum}
+	    cksum="shasum -a $cksum"
+	fi
 
 	local x="`$cksum "$1" | cut -f1 -d' '`"
 	if [ "$x" != "$y" ]; then
@@ -878,9 +878,9 @@ required() {
     # Choosen config must exist
     #
     if [ ! -f config/$config/packages ]; then
-        echo "ERROR: Config $config doesn't exist."
-        echo "ERROR: try scripts/Config -cfg $config first."
-        exit 1
+	echo "ERROR: Config $config doesn't exist."
+	echo "ERROR: try scripts/Config -cfg $config first."
+	exit 1
     fi
 
     while read on a b repo pkg c; do
