* implemmented "abort on error" supoprt for Emerge-Pkg on user request
git-svn-id: http://svn.exactcode.de/t2/trunk@11367 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Emerge-Pkg b/scripts/Emerge-Pkg
--- a/scripts/Emerge-Pkg
+++ b/scripts/Emerge-Pkg
@@ -220,9 +220,16 @@ echo "Packages scheduled to build: ${deplist:-none}"
 
 [ $update = 1 ] && options="$options -update"
 
+. config/$config/config
+
 for package in $deplist ; do
 	if ./scripts/Download $package ; then
-		./scripts/Build-Pkg $options $package
+		if ! ./scripts/Build-Pkg $options $package; then
+			if [ $SDECFG_ABORT_ON_ERROR_AFTER -gt 8 ]; then
+				echo "Aborting further builds due to config setting ABORT_ON_ERROR_AFTER."
+				exit 1
+			fi
+		fi
 	else
 		echo "The download for package $package failed!"
 		exit -1
