* fix scripts/Emerge-Pkg to not re-old-config on non existing pkgs 	* warn again on non existing deps, too
git-svn-id: https://svn.exactcode.de/t2/trunk@70987 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Emerge-Pkg b/scripts/Emerge-Pkg
--- a/scripts/Emerge-Pkg
+++ b/scripts/Emerge-Pkg
@@ -188,11 +188,24 @@ add_if_updated() {
 
 	[ $verbose = 1 ] && echo -n "$deptree: $pkg ..."
 
-	if [ $depth = 0 -a ! "${packages[$pkg]}" ]; then
-		# TODO: keep unselected in the config, to avoid re-config for masked pkgs
-		echo " Package not cached, re-reading config:"
-		scripts/Config -oldconfig -cfg $config
-		read_packages
+	# TODO: keep unselected in the config, to avoid re-config for masked pkgs
+	if [ -z "${packages[$pkg]}" ]; then
+	    if [ $depth = 0 ]; then
+		local desc=$(echo package/*/$pkg/$pkg.desc)
+		if [ -e "$desc" ]; then
+		    echo " Package not cached, re-reading config:"
+		    scripts/Config -oldconfig -cfg $config
+		    read_packages
+		fi
+
+		if [ -z "${packages[$pkg]}" ]; then
+		    echo " Error: No such package."
+		    exit 1
+		fi
+	    else
+		echo " Warning: No such package."
+		return
+	    fi
 	fi
 
 	if [ "${packages[$pkg]}" != X ]; then
