* fixed build_package error notification to actually work
git-svn-id: https://svn.exactcode.de/t2/trunk@14569 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/functions.in b/scripts/functions.in
--- a/scripts/functions.in
+++ b/scripts/functions.in
@@ -1077,12 +1077,15 @@ build_package()
 	dump_env > $builddir/debug.buildenv.$pkg
 
 	echo "Running main build function '$mainfunction' ..."
-
 	cd $builddir
-	if ! eval "$mainfunction" ; then
-		# just error, do not abort the build
-		echo_error "Warning: Failed building $xpkg!"
-	fi
+
+	# the reliable error catching is a bit tricky here ... if someone
+	# has a cleaner code chunk it is welcome
+	error=0; abort() { error=1 ; }
+	( eval "$mainfunction" )
+	[ $? -ne 0 ] && error=1
+	
+	[ $error = 0 ] || echo_error "Warning: Failed building $xpkg."
   )
 }
 
