* improved pkgprefix to have a 'testmode' (-t) 		* testmode aborts, use it outside `foo` calls. 		* returns PKGPREFIX_ERROR on errors on normal mode.
git-svn-id: https://svn.exactcode.de/t2/trunk@6878 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -432,39 +432,55 @@ pkginstalled() {
 	fi
 }
 
-# pkgprefix [<type>] <package>
+# pkgprefix [-t] [<type>] <package>
 # returns the prefix or the location of a 'type' of an already build package
 #
 pkgprefix() {
 	local type= pkg=
+	local dotest= abortmsg=
 	local prefix= value=
 
+	# -t : only see if it's possible to get the values
+	if [ "$1" = "-t" ]; then
+		dotest=1; shift
+	fi
+	
 	if [ $# -eq 2 ]; then
 		type="$1"; shift
 	fi
 	pkg="$1"
 
+	# test usual error causes
 	if [ -z "$pkg" ]; then
-		abort "pkgprefix: you must specify a package."
+		abortmsg="you must specify a package"
 	elif [ ! -f "$root/var/adm/packages/$pkg" ]; then
-		abort "pkgprefix: package $pkg is not present."
+		abortmsg="package $pkg is not present"
 	else
 		prefix=$( grep "^Prefix: " "$root/var/adm/packages/$pkg" | cut -d' ' -f2- )
 		if [ -z "$prefix" ]; then
-			abort "pkgprefix: $pkg record is old, please rebuild."
-		elif [ -z "$type" ]; then
-			echo "$prefix"
-		else
-			value=$( grep "^Location $type: " "$root/var/adm/packages/$pkg" | cut -d' ' -f2- )
-			if [ -z "$value" ]; then
-				value=$( xpkg="$pkg"; pkggetdir "$type" )
-			fi
-			if [ -z "$value" ]; then
-				abort "pkgprefix: type '$type' is not valid."
-			fi
-			echo "$value"
+			abortmsg="$pkg record is old, please rebuild"
 		fi
 	fi
+
+	if [ "$dotest" ]; then
+		# test mode: abort or continue
+		if [ "$abortmsg" ]; then
+			abort "pkgprefix: $abortmsg"
+		else
+			return 0
+		fi
+	elif [ "$abortmsg" ]; then
+		echo "pkgprefix: $abortmsg" 1>&2
+	elif [ -z "$type" ]; then
+		value="$prefix"
+	else
+		value=$( grep "^Location $type: " "$root/var/adm/packages/$pkg" | cut -d' ' -f3- )
+		if [ -z "$value" ]; then
+			# try default location for that $prefix
+			value=$( xpkg="$pkg"; pkggetdir "$type" )
+		fi
+	fi
+	echo "${value:-PKGPREFIX_ERROR}"
 }
 
 # pkggetdir <type>     (needs $prefix and $xpkg)
