* removed double slashes related to automatic doc copy
git-svn-id: https://svn.exactcode.de/t2/trunk@13574 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/functions.in b/scripts/functions.in
--- a/scripts/functions.in
+++ b/scripts/functions.in
@@ -791,9 +791,9 @@ build_this_package() {
 		fi
 
 		if [ "$createprefix" = 1 ]; then
-			echo "Creating $root/$prefix/<..> if required ..."
-			for x in $root/$docdir $root/$prefix/{bin,lib,share} \
-			         $root/$sysconfdir $root/$localstatedir
+			echo "Creating $root$prefix/<..> if required ..."
+			for x in $root$docdir $root$prefix/{bin,lib,share} \
+			         $root$sysconfdir $root$localstatedir
 			do
 				if [ ! -e $x ]; then
 					mkdir -p $x
@@ -875,9 +875,9 @@ build_this_package() {
 		fi
 
 		if [ "$createdocs" != 0 ]; then
-			if [ ! -e $root/$docdir ]; then
+			if [ ! -e $root$docdir ]; then
 				mkdir -p $docdir
-				rmemptydir="$rmemptydir $root/$docdir"
+				rmemptydir="$rmemptydir $root$docdir"
 			fi
 			[ -z "$createdocs" ] && createdocs="$SDECFG_CREATE_DOCS"
 		fi
@@ -900,7 +900,7 @@ build_this_package() {
 			[ "${x#*.info*}"    ] || continue
 			[ "${x#*.TAR*}"     ] || continue
 			[ "${x#*akefile*}"     ] || continue
-                        [ -f $x ] && cp -v $x $root/$docdir/$x
+                        [ -f $x ] && cp -v $x $root$docdir/$x
 		done
 
 		if [ "$createdocs" = 1 ]; then
@@ -910,16 +910,16 @@ build_this_package() {
 			               -o -name '[Dd]ocumentation' \) ! -empty`
 			do
 				if [ -d "$x" -a "`echo $x/*`" != "$x/*" ]
-				then cp -rLv $x/* $root/$docdir || true ; fi
+				then cp -rLv $x/* $root$docdir || true ; fi
 			done
 			for x in $confdir/*.doc; do
 				if [ -f $x ]
-				then cp -v $x $root/$docdir/${x%.doc}; fi
+				then cp -v $x $root$docdir/${x%.doc}; fi
 			done
-			find $root/$docdir/ -name '*.[0-9]' -o -name '*.info*' \
+			find $root$docdir/ -name '*.[0-9]' -o -name '*.info*' \
 				-o -name '[Mm]akefile*' |
 				xargs -r rm -f 2> /dev/null || true
-			find $root/$docdir/* -type d -empty 2> /dev/null |
+			find $root$docdir/* -type d -empty 2> /dev/null |
 				xargs -r rmdir 2> /dev/null || true
 		fi
 
