* improved pkgprefix usability, in test mode [-t] it no longer aborts 	  the build and thus can be used to test if a package is already 	  installed 	* shrinked pkgprefix message spit out for packages without a Prefix: 	  entry - those packages would be over 2 years old now and are rarely 	  experienced these days 	* finally improved pkgprefix to always abort early if misused (e.g. 	  argument count is not matching)
git-svn-id: https://svn.exactcode.de/t2/trunk@19766 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/functions.in b/scripts/functions.in
--- a/scripts/functions.in
+++ b/scripts/functions.in
@@ -497,8 +497,10 @@ pkginstalled() {
 	fi
 }
 
-# pkgprefix [-t] [<type>] <package>
-# returns the prefix or the location of a 'type' of an already build package
+# pkgprefix [-t] [ <type> ] <package>
+# Returns the prefix or the location of a 'type' of an already built package,
+# or aborts the build if not yet installed.
+# When run in the test mode [-t] it returns an error code accordingly.
 #
 pkgprefix() {
 	local type= pkg=
@@ -517,19 +519,20 @@ pkgprefix() {
 
 	# test usual error causes
 	if [ -z "$pkg" ]; then
-		abortmsg="you must specify a package"
+		abort "pkgprefix: you must specify a package"
 	elif [ ! -f "$root/var/adm/packages/$pkg" ]; then
 		abortmsg="package $pkg is not present"
 	elif grep -q "^Prefix:" "$root/var/adm/packages/$pkg"; then
 		prefix=$( grep "^Prefix: " "$root/var/adm/packages/$pkg" | cut -d' ' -f2- )
 	else
-			abortmsg=`echo "$pkg record is old, please rebuild the package $pkg. As an alternative, you can insert a line into the file $root/var/adm/packages/$pkg containing the text below:\n\nPrefix: <prefix>" | fmt -w 55 | sed 's,$,\\n,g'`
+		abort "pkgprefix: $pkg record is to old (no Prefix: entry), please rebuild it."
 	fi
 
 	if [ "$dotest" ]; then
 		# test mode: abort or continue
 		if [ "$abortmsg" ]; then
-			abort "pkgprefix: $abortmsg"
+			echo "pkgprefix: $abortmsg" 1>&2
+			return 1
 		else
 			return 0
 		fi
