* allow Update-Pkg continue updating cv-groups and count and print errors at the end
git-svn-id: https://svn.exactcode.de/t2/trunk@80771 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/scripts/Update-Pkg b/scripts/Update-Pkg
--- a/scripts/Update-Pkg
+++ b/scripts/Update-Pkg
@@ -95,13 +95,14 @@ update_pkg() {
 	# Step 2: Use the modified package descriptor to download
 	# the package. Again, nothing more that calling an existing
 	# script.
-	scripts/Download $pkg || exit 1
+	scripts/Download $pkg || return 1
 
 	# Third and final step is updating the checksum for the
 	# new download.
 	scripts/Create-CkSumPatch "$pkg" | patch -p0
 }
 
+errors=0
 # check if pkg exists
 if [ -d package/*/$pkg ]; then
 	update_pkg $pkg $ver
@@ -110,11 +111,17 @@ else
 	pkgs=$(grep "^\[CV-GROUP\] $pkg" package/*/*/*.desc | cut -d / -f 3)
 	if [ "$pkgs" ]; then
 		for p in $pkgs; do
-			update_pkg $p $ver
+			update_pkg $p $ver || ((++errors))
 		done
 	else
 		echo "ERROR: package $pkg doesn't exist"
+		((++error))
 		pkg=$(pkgsimilar $pkg)
 		[ "$pkg" ] && echo "Did you mean: $pkg?"
 	fi
+fi
+
+if [ $errors -gt 0 ]; then
+	echo "$errors errors."
+	exit 1
 fi
