* updated magicolor2430DL (1.1.0 -> 1.5.0)
git-svn-id: https://svn.exactcode.de/t2/trunk@14724 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/package/printing/magicolor2430DL/trivialities.patch b/package/printing/magicolor2430DL/trivialities.patch
--- a/package/printing/magicolor2430DL/trivialities.patch
+++ b/package/printing/magicolor2430DL/trivialities.patch
@@ -18,28 +18,31 @@ Some obvious first look / build fixes.
 
   - Rene Rebe <rene@exactcode.de>
 
---- magicolor2430DL-1.1.0/Makefile	2004-09-18 02:33:59.000000000 +0200
-+++ magicolor2430DL-1.1.0-fixed/Makefile	2005-02-23 08:34:34.284308864 +0100
-@@ -2,8 +2,8 @@
- CFLAGS	=	$(RC_CFLAGS)  -I. -I../include
- OPTIM	=	-Wall -fPIC -O2
- #OPTIM	=	-g
--LDLIBS	=	-lcups -lcupsimage
--LDADD	=	/usr/lib/liblcms.a /usr/local/lib/libjbig.a
-+LDLIBS	=	-lcups -lcupsimage -llcms -ljbig
-+LDADD	=	
- 
- MYPRINTER = /usr/local/KONICA_MINOLTA/mc2430DL
- 
-diff -ur magicolor2430DL-1.1.0/kmlf.h magicolor2430DL-1.1.0-fixed/kmlf.h
---- magicolor2430DL-1.1.0/kmlf.h	2004-09-02 20:18:38.000000000 +0200
-+++ magicolor2430DL-1.1.0-fixed/kmlf.h	2005-02-23 09:04:44.613097056 +0100
-@@ -33,7 +33,7 @@
- }IMAGEHEADER, *PIMAGEHEADER;
- #pragma pack()
- 
--#define arch_is_big_endian 0
-+#define arch_is_big_endian __BIG_ENDIAN__
- #define PRINTER_MODEL	"mc2430DL"
- 
- #ifdef __linux
+--- magicolor2430DL-1.5.0/configure.vanilla	2006-01-11 14:31:58.000000000 +0100
++++ magicolor2430DL-1.5.0/configure	2006-01-11 14:37:21.000000000 +0100
+@@ -3213,11 +3213,7 @@
+ echo "$as_me:$LINENO: result: $ac_cv_lib_jbig_jbg_enc_init" >&5
+ echo "${ECHO_T}$ac_cv_lib_jbig_jbg_enc_init" >&6
+ if test $ac_cv_lib_jbig_jbg_enc_init = yes; then
+-  if test -f "/usr/lib/libjbig.a"; then
+-	LIBJBIG="/usr/lib/libjbig.a"
+-else
+-	LIBJBIG="/usr/local/lib/libjbig.a"
+-fi
++	LIBJBIG="-ljbig"
+ else
+   { { echo "$as_me:$LINENO: error: Could not find libjbig.a" >&5
+ echo "$as_me: error: Could not find libjbig.a" >&2;}
+@@ -3290,11 +3286,7 @@
+ echo "$as_me:$LINENO: result: $ac_cv_lib_lcms_cmsCreateTransform" >&5
+ echo "${ECHO_T}$ac_cv_lib_lcms_cmsCreateTransform" >&6
+ if test $ac_cv_lib_lcms_cmsCreateTransform = yes; then
+-  if test -f "/usr/lib/liblcms.a"; then
+-	LIBLCMS="/usr/lib/liblcms.a"
+-else
+-	LIBLCMS="/usr/local/lib/liblcms.a"
+-fi
++	LIBLCMS="-llcms"
+ else
+   { { echo "$as_me:$LINENO: error: Could not find liblcms.a" >&5
+ echo "$as_me: error: Could not find liblcms.a" >&2;}
