* fixed stray install/init error message printout, regression in r37647
git-svn-id: https://svn.exactcode.de/t2/trunk@45597 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/target/share/install/init b/target/share/install/init
--- a/target/share/install/init
+++ b/target/share/install/init
@@ -275,8 +275,10 @@ load_ramdisk_file()
 
 	echo "Extracting second stage filesystem ..."
 	filter=`filter_for "$filename"`
-	$filter < /mnt_source/$filename | ( cd /mnt_root; tar x )
-	echo "Can't run tar on $fielname."
+	if ! $filter < /mnt_source/$filename | ( cd /mnt_root; tar x ); then
+		echo "Can't run tar on $fielname."
+		exit_linuxrc=0
+	fi
 	
 	umount /mnt_source || exit_linuxrc=0
 	rmdir /mnt_source || exit_linuxrc=0
