* let install/init recover gracefully if no 2nd stage image was 	  retrieved via the network or from cdrom (formerly it let the 	  kernel panic due dieing init when no 2nd stage executable is 	  around ...) 	* renamed 1st,2nd stage to first/second stage for a more uniform, 	  professional look 	* fixed network interface question to have the user input on 	  the same line
git-svn-id: https://svn.exactcode.de/t2/trunk@18229 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/target/share/install/init b/target/share/install/init
--- a/target/share/install/init
+++ b/target/share/install/init
@@ -105,7 +105,9 @@ select_2nd_stage()
 		;;
 	esac
 
-	echo "Select a stage 2 image file:"
+	[ "$images" ] || return 1
+
+	echo "Select a second stage image file:"
 	mem=`sed -n '/MemTotal/{s/.* \([[:digit:]]*\) .*/\1/p}' /proc/meminfo`
 	i=1; default=$i
 	for x in $images; do
@@ -142,6 +144,10 @@ httpload()
 	[ "$baseurl" ] || return
 
 	select_2nd_stage "$baseurl" filename
+	if [ -z "$filename" ]; then
+		echo "Failure retrieving the second stage image."
+		return
+	fi
 
 	exit_init=1
 	url=$baseurl/$filename
@@ -156,7 +162,7 @@ httpload()
 
 	fget $url | ( cd /mnt_root; tar x ) # -z
 	
-	echo "finished ... continuing execution of 2nd stage"
+	echo "finished ... continuing execution of second stage"
 	doboot
 }
 
@@ -241,7 +247,7 @@ load_ramdisk_file()
 	devicefile=
 	filename=
 
-	echo -e "\nSelect a device for loading the 2nd stage system from:\n"
+	echo -e "\nSelect a device for loading the second stage system from:\n"
 
 	getdevice devicefile
 	if [ -z "$devicefile" ]; then
@@ -250,6 +256,10 @@ load_ramdisk_file()
 	fi
 
 	select_2nd_stage $devicefile filename
+	if [ -z "$filename" ]; then
+		echo "No image found."
+		return
+	fi
 
 	exit_linuxrc=1
 	echo "Using $devicefile:$filename"
@@ -260,7 +270,7 @@ load_ramdisk_file()
 	mkdir /mnt_root || exit_linuxrc=0
 	mount none /mnt_root -t tmpfs || exit_linuxrc=0
 
-	echo "Extracting 2nd stage filesystem ..."
+	echo "Extracting second stage filesystem ..."
 	cat /mnt_source/$filename | ( cd /mnt_root; tar x ) || # -z
 	echo "Can't run tar on $fielname."
 	
@@ -284,7 +294,7 @@ net_config()
 {
 	echo -n "Interfaces: "; ls -A /sys/class/net/
 
-	echo "Enter interface name (eth0): "
+	echo -n "Enter interface name (eth0): "
 	read dev ; [ "$dev" ] || dev="eth0"
 	ipconfig -d $dev -t 20
 
@@ -328,13 +338,13 @@ T2 SDE installer (1st stage - loader) ...
 
 The T2 install system boots up in two stages. You are now in the first stage
 and if everything goes right, you will not spend much time here. Just 
-configure the installation source so the 2nd stage boot system can be loaded
-and you can start the installation."
+configure the installation source so the second stage boot system can be
+loaded and you can start the installation."
 exit_init=0
 while [ $exit_init = 0 ]; do
 	echo -n "
-     0. Load 2nd stage system from local device
-     1. Load 2nd stage system from network
+     0. Load second stage system from local device
+     1. Load second stage system from network
      2. Configure network interfaces
      3. Load kernel modules from this disk
      4. Load kernel modules from another disk
