* improved shared/install/init stage2 decompression fail error handling
git-svn-id: https://svn.exactcode.de/t2/trunk@52816 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/target/share/install/init b/target/share/install/init
--- a/target/share/install/init
+++ b/target/share/install/init
@@ -3,6 +3,7 @@
 # T2 SDE: target/share/install/init
 # Partially based on linuxrc.c, Copyright (C) 2003, 2004 Clifford Wolf and Rene Rebe
 # Converted from C to shell, heavily cleaned and improved for the T2 SDE by:
+# (C)2005-2021 Rene Rebe, ExactCODE GmbH; Germany.
 
 # Only print important stuff to console
 # klogctl(8, NULL, 3);
@@ -125,7 +126,11 @@ httpload() {
 	mv /bin/{,.}tar
 	for f in $filename; do
 		url=$baseurl/$f
-		fget $url | $filter | (cd /; .tar x)
+		if ! fget $url | $filter | (cd /; .tar x); then
+			echo "ERROR EXTRacting $f."
+			mv /bin/{.,}tar
+			exit_linuxrc=0
+		fi
 	done
 	rm /bin/.tar
 
@@ -244,6 +249,7 @@ load_ramdisk_file() {
 	for f in $filename; do
 		if ! $filter < /media/$f | (cd /; .tar x); then
 			echo "Error extracting $f."
+			mv /bin/{.,}tar
 			exit_linuxrc=0
 		fi
 	done
