* depmod needs to know the System.map, and for 2.4.* series, 	  -ae must be supplied as argument
git-svn-id: https://svn.exactcode.de/t2/trunk@9908 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/package/base/sysfiles/mkinitrd b/package/base/sysfiles/mkinitrd
--- a/package/base/sysfiles/mkinitrd
+++ b/package/base/sysfiles/mkinitrd
@@ -26,6 +26,16 @@ if [ ! -d $moddir ]; then
 	exit 2
 fi
 
+sysmap=""
+[ -f "/boot/System.map_$kernelver" ] && sysmap="/boot/System.map_$kernelver"
+
+if [ -z "$sysmap" ]; then
+	echo "System.map_$kernelver not found!"
+	exit 2
+fi
+
+echo "System.map: $sysmap"
+
 tmpdir=`mktemp`
 
 # create basic structure
@@ -64,7 +74,7 @@ done
 
 # generate map files
 #
-/sbin/depmod --basedir $tmpdir $kernelver
+/sbin/depmod -ae -b $tmpdir -F $sysmap $kernelver
 
 echo "Injecting programs and configuration ..."
 
