* check for cpio and gzip in mkinitrd, they might be missing and with 	  the redirection the shell will not abort when one of them is missing 	  during archiving
git-svn-id: http://svn.exactcode.de/t2/trunk@14122 c5f82cb5-29bc-0310-9cd0-bff59a50e3bc

diff --git a/package/base/sysfiles/mkinitrd b/package/base/sysfiles/mkinitrd
--- a/package/base/sysfiles/mkinitrd
+++ b/package/base/sysfiles/mkinitrd
@@ -36,6 +36,14 @@ fi
 
 echo "System.map: $sysmap"
 
+# check needed tools
+for x in cpio gzip ; do
+	if ! which -p $x ; then
+		echo "$x not found!"
+		exit 2
+	fi
+done
+
 tmpdir=`mktemp`
 
 # create basic structure
